### ISSUE TITLE
Epic: Ansible collection compatible repository layout

### ISSUE THREAD

**Issue by erikgb** [confluentinc/cp-ansible#613]
Thanks a lot for super useful collection of ansible roles and playbooks! ❤️ But to be honest, I am sick and tired of using the pesky and partially broken Git submodules. 😡 To mend this, I hereby suggest this epic issue of making this repository compatible with the [Ansible collection repository layout](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html).

Apart from being a big step towards resolving https://github.com/confluentinc/cp-ansible/issues/113, I see the following benefits of doing this:
- Enforcing a standard directory layout will make it more obvious where new things should be added.
- The `ansible-galaxy` CLI also supports Git repository references (branch, tag, commit) to install collections (and roles). This will make it a lot easier to install cp-ansible and use it as a part of a bigger Ansible setup (as we do with submodule now).

I had look on what would need to be done, and I noted this (please add if I missed something):

- [x] Add `galaxy.yml` to the repository root. The content of this file will define the collection coordinates, and how a user would refer to collection contents. Will use `namespace: confluent` and `name: platform`. (https://github.com/confluentinc/cp-ansible/pull/623). To use a role, using Kafka Broker as an example, this could look like this:
    ```yaml
    roles:
      - role: confluent.kafka.kafka_broker
    ```
- [x] Move/refactor the test scenarios out to a top level molecule directory. I do not think they should be mixed into the collection roles. (https://github.com/confluentinc/cp-ansible/pull/701)
- [x] Rename roles to "simple" names. 'The character `.` is not allowed in collection role names. And the collection will namespace the roles anyway. (https://github.com/confluentinc/cp-ansible/pull/624)
- [x] Move playbooks with tasks directory to a new playbooks directory. (https://github.com/confluentinc/cp-ansible/pull/730)
- [x] Move/refactor `roles/confluent.variables/filter_plugins` to `plugins/filter` (collection roles are not allowed to contain plugins) (https://github.com/confluentinc/cp-ansible/pull/631)
- [x] Update relative imports work in collections to start with a period (`.`). This is detailed in 3. [here](https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html#migrating-other-role-plugins-to-a-collection). (https://github.com/confluentinc/cp-ansible/pull/709)
- [x] Convert molecule scenarios to test collections. Jeff Geerling has written an [excellent blog post](https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule) about adding molecule integration tests to Ansible collections. (https://github.com/confluentinc/cp-ansible/pull/631)
- [x] Update Dev Guide, calling out that we are using Ansible collections, and all custom plugins must use FQPN (https://github.com/confluentinc/cp-ansible/pull/729)
- [x] Move test roles into own roles dir. We do not want to "ship" our testing roles with the collection. (https://github.com/confluentinc/cp-ansible/pull/734)

The Ansible dev documentation on [migrating roles to collections](https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html#migrating-a-role-with-plugins-to-a-collection) might be useful for this migration.

I would be happy to help with this migration, but I think it should be coordinated by maintainers. Rebasing a refactor PR branch can be very annoying, and we must also ensure that any fixes done in cp-ansible are not "lost in refactoring". And personally, I would also say that fixing https://github.com/confluentinc/cp-ansible/issues/551 is a requirement for heavy contribution...

**Comment by domenicbove** [comment]
@piif We are investigating refactoring cp-ansible into an Ansible collection in our next major release. Unfortunately it seems the minimum version for collections is Ansible 2.9. Can you weigh in on whether you'll be able to upgrade ansible versions by early summer?

**Comment by erikgb** [comment]
I've had a closer look at the changes required to be able to use cp-ansible as an Ansible collection, and most of the changes are pretty straightforward.

The most challenging issue IMO, is that filters must the referenced by their FQCN to work from within a collection. The reasons are elaborated by an Ansible maintainer in this closed issue comment: https://github.com/ansible/ansible/issues/58629#issuecomment-509390379. Changing this, will probably make it impossible to use cp-ansible just as according to the [official documentation](https://docs.confluent.io/ansible/current/overview.html). And that is 👎 .

The other delicate matter, is that in cp-ansible, the playbooks are actually very valuable. They are able to orchestrate a smart rolling deployment strategy which has proven very valuable in our GitOps CI/CD approach. IMO the most common reuse pattern in Ansible is reusing roles, but the rolling strategy implemented in cp-ansible cannot be encapsulated by a role. And [publishing playbooks from Ansible collections](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#playbooks-directory) is officially still TBD. But there seems to be ongoing/finished work that will hopefully be released with the next version of Ansible (4.x; ansible-core 2.11). Here is the relevant PR: https://github.com/ansible/ansible/pull/67435. When this released, it should be possible to use cp-ansible almost as today. Could be as easy as this:

```shell
$ ansible-galaxy collection install git+https://github.com/confluentinc/cp-ansible.git,6.2.0
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'confluent.platform:6.2.0' to '~/.ansible/collections/ansible_collections/confluent/kafka'
Created collection for confluent.platform at ~/.ansible/collections/ansible_collections/confluent/kafka
confluent.platform (6.2.0) was installed successfully
$ ansible-playbook confluent.platform.all -i hosts.yml
```

Anyone watching cp-ansible that have comments on the way forward here?

**Comment by domenicbove** [comment]
@erikgb Thanks for all your investigation/ work on this. The main contract we have right now, that I think we need to preserve, is around our playbooks. The filter names can change. The roles even we should be able to change, but it is expected that all.yml exists in some fashion calling our roles. So we will need to get creative around https://github.com/ansible/ansible/pull/67435

And especially because the rolling restart logic exists in the playbooks, they can't be lost.

I am also excited to hear that you do not actually need to push your collection to galaxy. GH should be enough. Keep up the great work.

**Comment by domenicbove** [comment]
Playbooks are included in collections starting w 2.11: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-a-playbook-from-a-collection

This may fully unblock us from proceeding with this issue!

**Comment by domenicbove** [comment]
More (potentially optional) tasks

- [ ] Refactor all module invocations to use collections pattern
- [ ] Update Docs to show how to use playbooks from collections
Should look like
```
ansible-playbook -i hosts.yml confluent.platform.all.yml
```

**Comment by domenicbove** [comment]
Adding more required tasks:
- [ ] Update Dev Guide, calling out that we are using Ansible collections, and all custom plugins must use FQPN
- [ ] Update Official docs on docs.confluent.io for new collections usage

**Comment by erikgb** [comment]
I think this issue (epic) can be closed! 🚀 I am able to successfully provision our clusters using cp-ansible as an Ansible collection from 7+ branches. Thanks a lot for the cooperation @domenicbove! 🙏
